### ISSUE TITLE
Authentication token manipulation error when trying to set password for new user

### ISSUE THREAD

**Issue by DimosthenisK** [aniongithub/pi-bootstrap#15]
This is the error I'm getting:
![image](https://user-images.githubusercontent.com/32791127/152991375-de9ef8a1-a4e7-413b-83b3-4a7a4e9d3711.png)

I am trying to run the script inside WSL. The image is generated as expected (but obviously I can't login because the password wasn't being set) when I run with 
```
RUN << EOF &> /dev/null
bash -c "echo ${user}:${password} | chpasswd"
EOF
```
because the error output is ignored, but when I remove that, I can see the error.

I also see exactly the same error when trying to run with remotely with github actions.

Also, not sure if that's related, but I had to switch the path in core.Pifile because $dir returned the directory of the modules instead of the root directory of the project, leading to the .env file to not be acknowledged.
```
root_pifile=$1
dir="$(dirname $root_pifile)/.." # <- This is what changed
if [ -f "$dir/.env" ]; then
    # Set up environment configured in our env file
    # https://unix.stackexchange.com/a/79077/358706
    set -o allexport
    . $dir/.env
    set +o allexport
fi

if [ -f "$dir/secrets.env" ]; then
    # Set up environment configured in our env file
    # https://unix.stackexchange.com/a/79077/358706
    set -o allexport
    . $dir/secrets.env
    set +o allexport
fi
```

Any ideas? I can't seem to fix the issue on my own, as I can't pinpoint if it's an issue with pimod, with pi-bootstrap, with the base image I'm using or something else entirely. This happens both with the pi-bootstrap provided base image (`FROM https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip`) and with the latest one (`FROM https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-01-28/2022-01-28-raspios-bullseye-armhf-lite.zip`). It also happens both in my project and in this one https://github.com/aniongithub/rhasspy-appliance

**Comment by aniongithub** [comment]
@DimosthenisK Sorry I missed this! Were you able to resolve the issue? It'd help if you shared what the problem was as others might run into it too!
